import { Geist, Geist_Mono, Dancing_Script, Big_Shoulders_Inline_Text, Courier_Prime, Cormorant_Garamond, PT_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/common/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dancing = Dancing_Script({ variable: "--font-dancing", subsets: ["latin"], weight: "700" })
const courier = Courier_Prime({ variable: "--font-courier", subsets: ["latin"], weight: "400" })
const big_shoulders = Big_Shoulders_Inline_Text({ variable: "--font-big-shoulders", subsets: ["latin"], weight: "700" })
const garadmont = Cormorant_Garamond({ variable: "--font-cormorant", weight: "700", subsets: ["latin", "cyrillic"] })
const pt_mono = PT_Mono({variable: "--font-pt-mono", subsets: ["latin", "cyrillic"], weight: "400"})

export const metadata = {
  title: "Беззаперечне Полотно",
  description: "Generated by banew",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancing.variable} ${big_shoulders.variable} ${courier.variable} ${garadmont.variable} ${pt_mono.variable}`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
